### ISSUE TITLE
Wot is this lol

### ISSUE THREAD

**Issue by BSFishy** [InconspicuousCommunism/frendr#2]
I saw this on the board in comp sci
I want to help but don't know wot this is

**Comment by AeonEcho** [comment]
The social network to end all social networks 
Twitter who
Facebook who
Development hasn't started yet, but keep an eye on the repo.

**Comment by BSFishy** [comment]
I can help with general styling

I guess u could say I'm proficient in html & case, and depending on what back end you choose, php 2

I'll try to make a wip pull request tonight

**Comment by BSFishy** [comment]
Another thing to think about is the git workflow. You can do some research on them [here](https://www.atlassian.com/git/tutorials/comparing-workflows), but I recommend [this one](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).

Libraries and stuff can be helpful too. [SCSS](https://sass-lang.com/) is a nice one, and for the interface, [material design lite](https://getmdl.io/) looks good. Just some things to think about.
